/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * describes a event in time, with a duration and action
 */
export interface EventSchema {
    event_id: string;
    action_type: "OTHER" | "SKILL" | "SKILLCATEGORY" | "XP" | "TASK";
    action?:
        | "OTHER"
        | "FINISHED"
        | "CREATED"
        | "STARTED"
        | "DELETED"
        | "EDITED";
    xp_amount?: number;
    start_time: number;
    duration?: number;
    task_id?: string | null;
    [k: string]: unknown;
}
