/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { TaskDocument } from "./task.schema";

/**
 * describes a skill
 */
export interface SkillSchema {
    id: string;
    display_name: string;
    color?: string;
    xp_amount: number;
    expected_completion_time?: number;
    index?: number;
    category_id?: string;
    tasks?: string[];
    tasks_?: Promise<TaskDocument[]>;
}
