/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * describes a task
 */
export interface TaskSchema {
    id: string;
    display_name: string;
    skill?: string | null;
    category?: string | null;
    completed?: boolean;
    completion_time?: number;
    deadline_time?: number;
    color?: string | null;
    xp_worth?: number;
    [k: string]: unknown;
}
